footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.02

robot_base_frame: base_link
update_frequency: 4
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.025

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan_with_noise, inf_is_valid: true}

inflation:
    inflation_radius: 1.3
    cost_scaling_factor: 9 # default is 10
